services:
  - name: twitterfromtemu
    type: web
    env: python
    buildCommand: | 
      echo "go fuck yourself render"
      cd frontend
      npm install
      npm run build
      cd ..
      pip install -r backend/requirements.txt
    startCommand: "gunicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: temu_twitterdb
          property: connectionString
      - key: SECRET_KEY
        sync: false  
databases:
  - name: temu_twitterdb
    type: postgresql